cat << _EOF_

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="This is a simple html page auto-generated by shell script, containing summary of a lecture and its word cloud."/>
		<meta name="author" content="Yours truly-- NAKUL AGARWAL" />
		
		<title>Lecture Notes</title>
		
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<!-- jQuery library -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
		<!-- Latest compiled JavaScript -->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	</head>
	
	<body>
		<div class="fullpage" style="padding-top:10vh;">
			<div class="main" style="height:75vh;">
				<div class="row" style="margin:0; padding:0">
					<div class="col-sm-6">
						<img src="word_cloud.png" style="width:100%"/>
					</div>
					<div class="col-sm-6">
						<p style="font-family: 'Raleway', sans-serif; font-size:2vmin;">
_EOF_
